version: "3.3"
services:
  dpapi:
    ports:
      - 443:443

  proxy:
    environment: 
      NODE_ENV: development
    volumes:
      - nodproxy_node_modules:/app/node_modules
      - ../node-proxy:/app

  jenkins:
    ports:
      - 8080:8080

volumes:
  nodproxy_node_modules: {}
