version: "3.3"
services:
  dpapi:
    ports:
      - 443:443

  proxy:
    restart: always
    environment: 
      NODE_ENV: production
    ports: 
      - 80:80
    # command: nodemon index.coffee

  jenkins:
    ports:
      - 8080:8080
