version: "3.3"
services:
  app:
    image: ${IMAGE_NAME}-script-app
    build: 
      context: ./app
      dockerfile: ../Dockerfile
    network_mode: bridge
    working_dir: /app
    volumes: 
      - app_node_modules:/app/node_modules
      - ./app:/app

volumes:
  app_node_modules: {}