version: "3.3"
services:
  app:
    image: ${IMAGE_NAME}-script-app
    build: 
      context: ./app
    network_mode: bridge
    volumes: 
      - app_node_modules:/app/node_modules
      - ./app:/app

  oauth2:
    image: ${IMAGE_NAME}-script-auth
    network_mode: bridge
    build: 
      context: ./auth
    #entrypoint: coffee index.coffee
    volumes: 
      - auth_node_modules:/auth/node_modules
      - auth_data:/data
      - ./auth/client_secret.json:/client_secret.json:ro
      - ./auth:/auth


volumes:
  app_node_modules: {}
  auth_node_modules: {}
  auth_data: {}