version: "3.3"
services:
  app:
    image: ${IMAGE_NAME}-script-app
    network_mode: bridge
    build: 
      context: ./app
    #entrypoint: coffee index.coffee
    volumes: 
      - app_node_modules:/app/node_modules
      - auth_data:/data
      - ./app/client_secret.json:/client_secret.json:ro
      - ./app:/app


volumes:
  app_node_modules: {}
  auth_data: {}