version: "3"
services:
  app:
    ports:
      - 8800:80
    volumes:
      - ../app:/app
      - app_node_modules:/app/node_modules
    command: nodemon index.coffee

  deploy:
    volumes: 
      - ../_common.sh:/_common.sh
      - ../app/deploy.sh:/deploy.sh
    
volumes:
  app_node_modules: {}